# Generated by Django 4.1 on 2022-08-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=100)),
                ('fish_record', models.CharField(max_length=100)),
                ('fish_docs', models.TextField()),
                ('fish_pic', models.CharField(max_length=100)),
            ],
        ),
    ]
