# Generated by Django 4.1 on 2022-08-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_finder_app', '0002_fishdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishdb',
            name='fish_record',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
